rvm_2_1_1/current/config/routes.rb
InquirlyNew::Application.routes.draw do

  #### Landing Page and Auth Routes ####

  devise_scope :user do
    authenticated :user do
      root 'application#home', as: :authenticated_root
    end

    unauthenticated :user do
      root  'home#index'
    end
  end
  
  devise_for :users, :controllers => {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations", unlocks: "users/unlocks"}, :path_names => {sign_in: "login", sign_up: "register"}

  devise_scope :user do
    match "/users/auth/facebook/callback", :to => "users/omniauth_callbacks#facebook", via: :get
    match '/users/auth/twitter/callback' => "users/omniauth_callbacks#twitter", via: :get
    match '/users/auth/google_oauth2/callback' => "users/omniauth_callbacks#google", via: :get
    match '/users/auth/linkedin/callback' => "users/omniauth_callbacks#linkedin", via: :get
    match 'auth/:provider/failure', :to => "users/omniauth_callbacks#failure", via: :get
    match '/users/confirmation', :to => "users/confirmations#create", :via => :post
    match '/users/confirmation/new', :to => "users/confirmations#new", :via => :get
    match '/users/confirmation', :to => "users/confirmations#show", :via => :get
    match '/users/validate_user', :to => "users/sessions#validate_user_data", :via => :post
    match '/users/fb_pages', :to => "users/omniauth_callbacks#fb_pages", :via => :get
    match '/users/save_fb_pages', :to => "users/omniauth_callbacks#save_fb_pages", :via => :post
    match '/users/remove_fb_session', :to => "users/omniauth_callbacks#remove_fb_session", :via => :get
    match '/users/linkedin_pages', :to => "users/omniauth_callbacks#linkedin_pages", :via => :get
    match '/users/save_linkedin_pages', :to => "users/omniauth_callbacks#save_linkedin_pages", :via => :post
    match '/users/remove_linkedin_session', :to => "users/omniauth_callbacks#remove_linkedin_session", :via => :get
  end

  resources :home do
    collection do
      get 'signup', to: 'home#signup_form'
      get 'signin', to: 'home#signin_form'
      get 'forgot_password', to: 'home#forgot_password_form'
      post 'save_referrer'
      post 'fetch_short_url'
    end
  end

  get '/signup' => 'home#signup_form'
  get '/shorten_link' => 'home#shorten_link'

  #### Admin Login Routes ####

  namespace :admin do
    resources :pricing_plans
    resources :permissions
    resources :action_lists
    resources :client_settings do
      collection do
        get 'user_client_settings'
      end
    end
    resources :users, controller: "manage_users" do
      collection do
        post 'change_status'
      end
    end
    resources :manage_clients do
      collection do
        get 'plan_settings'
        get 'client_plan_details'
        post 'change_client_status'
        post 'save_client'
        post 'save_client_company'
        post 'save_client_pricing_plan'
        get 'client_signup'
        post 'update_client_company'
      end
      get 'show_users'
      get 'show_tenants'
      get 'edit_tenant'
      put 'update_tenant'
      get 'download_client_detail'
    end
  end
  match 'admin/manage_clients/:client_id/client_company', :to => "admin/manage_clients#client_company", via: :get
  match 'admin/manage_clients/:client_id/client_pricing_plan', :to => "admin/manage_clients#client_pricing_plan", via: :get

  resources :payments do
    collection do
      post 'update_payment_details'
      get 'get_user_emails'
    end
  end

  #### EMail and SMS Blast API Routes ####

  namespace :api do
    resources :campaigns do
      collection do
        post 'email_blast'
        post 'sms_blast'
      end
    end
  end

  resources :manage_roles do
    collection do
      post 'update_permissions'
      get 'role_permissions'
    end
  end

  #### Mobile API Routes ####

  namespace :rest do
    devise_for :session do
      post '/authenticate',  to:'sessions#create'
    end
    match '/getConfigData', to: 'power_share#social_accounts', as: :social_accounts, via: :post
    match '/powerShare', to: 'power_share#power_share', as: :power_share, via: :post
    match '/getShareQueue', to: 'power_share#get_share_queue', as: :get_share_queue, via: :post
    match '/getShareHistory', to: 'power_share#get_share_history', as: :get_share_history, via: :post
    match '/getReachData', to: 'power_share#get_reach_data', as: :get_reach_data, via: :post
    match '/deletePost', to: 'power_share#delete_post', as: :delete_post, via: :post
    match '/reschedulePost', to: 'power_share#reschedule_post', as: :reschedule_post, via: :post
    match '/getS3Config', to: 'power_share#get_s3_config', as: :get_s3_config, via: :post
    match '/getRecipients', to: 'power_share#get_recipients', as: :get_recipients, via: :post
    match '/getCampaigns', to: 'power_share#get_campaigns', as: :get_campaigns, via: :post
    match '/getSessionInfo', to: 'power_share#get_session_info', as: :get_session_info, via: :post
    match '/updateCampaignState', to: 'power_share#update_campaign_state', as: :update_campaign_state, via: :post
    match '/getApprovalPost', to: 'power_share#get_approval_post', as: :get_approval_post, via: :post
  end

  ##### Angular Routes ####

  resources :configurations do
    collection do
      get 'social_configure'
      post 'customise_campaign'
      get 'get_campaign_styles'
      get 'get_user_actions'
      get 'beacons_list'
      post 'create_beacon'
      post 'update_beacon'
      post 'change_status'
      get 'qr_code_list'
      post 'create_qr_code'
      post 'update_qr_code'
      get 'download_qr_code'
      post 'change_qr_status'
      get 'get_schedule_types'
      post 'add_slot'
      post 'remove_slot'
      post 'update_active_days'
      post 'update_schedule'
      post 'save_schedule'
      post 'pricing_plan_configure'
    end
  end

  resources :companies do
    collection do
      get 'get_tags'
      post 'get_company_info'
    end
  end

  resources :account do
    collection do
      get 'payment_details'
      get 'user_settings'
      post 'update_password'
      post 'update_user_details'
      post 'upload_profile_image'
      post 'destroy_profile_image'
      get  'user_details'
      post  'invite_user'
      get 'user_permissions'
    end
  end

  resources :tenants do
    collection do
      post 'change_tenant_status'
      get 'check_caller_id'
      get 'check_verify_caller_ids'
      get 'load_geo_details'
      post 'create_tenant'
      post 'create_region'
      post 'create_type'
      get 'get_client_plan'
      post 'save_tenant_plan'
      get 'get_tenant_plan'
    end
  end

  resources :corporate_users do
    collection do
      get 'mapping_roles'
      post 'update_user_roles'
      post 'reset_password'
      post 'change_user_status'
      post 'create_user'
      post 'reset_user_password'
      get 'load_regions'
      get 'load_tenants'
    end
  end

  resources :inq_campaigns do
    collection do
      get 'user_channels'
      post 'update_campaign_state'
    end
  end
  
  resources :power_share do
    collection do
     get 'social_accounts'
     post 'fetch_meta_data'
     post 'share_content'
     get 'scheduled_campaigns'
     post 'reschedule_share'
     post 'remove_post'
     get 'power_share_history'
     post 'get_reach'
     post 'archive_post'
     post 'campaign_share'
     post 'remove_schedule'
     post 'get_campaign_channels'
     post 'post_info'
    end
  end

  resources :customers do
    collection do
      get 'get_customer_email'
      get 'email_duplication_check'
      get 'mobile_duplication_check'
      post 'delete_selected'
      post 'remove_social_account'
      get 'all_countries'
      get 'states'
      post 'update_config'
      post 'update_group_info'
      get 'contact_groups'
      get 'group_customers'
      post 'update_group_name'
      post 'remove_group'
      post 'remove_group_customer'
    end
  end

  resources :imports do
    collection do
      post 'create_customer_info'
      get 'csv_template'
      get 'get_upload_status'
    end
  end

  resources :email_activity do
    collection do
      post 'reject_list'
    end
  end

  resources :chat do
    collection do
      get 'identity'
    end
  end

  resources :alert_config do
    collection do
      post 'change_event_status'
      post 'change_channel_status'
      get 'alerts'
      post 'send_alerts'
      post 'update_view_status'
      post 'update_alert_config'
      post 'create_alert_event'
      post 'delete_alert_event'
      post 'get_alert_placeholders'
      post 'update_alert_event'
    end
  end

  resources :dashboard do
    collection do
      post 'get_businesses_info'
      post 'user_engaged_results'
      post 'planner_details'
      get 'post_reviews'
      get 'alerts'
      get 'post_revision'
      post 'get_revision_info'
      get 'get_piwik_info'
    end
  end
end

rvm_2_1_1/current/app/views/shared/_admin_menus_header.html.erb
<%  c = controller.controller_name %>
<%  a = controller.action_name %>
<ul class="nav nav-tabs main-tabs" id="myTab">
  <%# if is_permission_view("roles","index",current_user,session[:user_permissions]) %>
  <li class = "<%= c=="tenants" ? "active" : "" %>"><a href="/tenants" tabindex="9"><span class="glyphicon glyphicon-tower"></span>Manage Tenants</a></li>
	<%#end%>
  <%# if is_permission_view("corporate_users","index",current_user,session[:user_permissions]) %>
  <li class="<%= (c=="corporate_users" && (a == "new" || a == "edit" || a == "index" || a == "show" || a == "create" || a == "update") ) ? "active" : "" %>">
    <a href="/corporate_users" tabindex="1"><span class="glyphicon glyphicon-cog"></span>Manage Users</a></li>
<%#end%>
	<%# if is_permission_view("corporate_users","mapping_tenant",current_user,session[:user_permissions]) %>
  <li class=" <%= (c =="corporate_users" && a == "mapping_tenant") ? "active" : "" %>"><a  href="/corporate_users/mapping_tenant" class="account_nav_button billing" tabindex="12"><span class="glyphicon glyphicon-credit-card"></span>Manage Executives</a></li>

  <li class=" <%= (c =="manage_roles") ? "active" : "" %>"><a  href="/manage_roles" class="account_nav_button billing" tabindex="12"><span class="glyphicon glyphicon-credit-card"></span>Manage Roles</a></li>
	<%# end%>
</ul>

rvm_2_1_1/current/app/views/shared/_css_files_link.html.erb
<link rel="stylesheet" href="/ng-app/ang-styles/bootstrap.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/font-awesome.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/font-awesome.min.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/base.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/ng-tags-input.min.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/colorpicker.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/angular-ui-switch.min.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/base-dev.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/datetimepicker.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/angular-csp.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/deck-grid.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/angular-tour.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/angular-datepicker.min.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/fullcalendar.min.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/rzslider.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/codemirror.css"/>
<link rel="stylesheet" href="/ng-app/ang-styles/xq-light.css"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/listen_v2/static/css/v2/listen.css?v=1"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/campaigns/static/css/card.css?v=1"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/campaigns/static/css/template.css?v=1"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/campaigns/static/css/campaign.css?v=1"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/campaigns/static/css/e-catalouge.css?v=1"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/campaigns/static/css/textAngular.css"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/campaigns/static/css/spectrum.min.css"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/pipeline2/static/css/pipeline.css"/>
<link rel="stylesheet" href="<%= ENV['V2_LISTEN_URL']%>/listen_v2/static/css/v2/angucomplete-alt.css"/>

rvm_2_1_1/current/app/views/shared/_edit_permissions.html.erb
<div class="tab-content inner">
  <div class="tab-wrapper">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
        <%= form_for :feature, :url => {:action => 'update'},:method => :put, :class => "form-inline"  do |f|%>
            <%@parent_features.each do |feature| %>
             <div class="field" >
               <div class="col-sm-6 col-md-6 col-lg-6 Pr0">
                  <% p_access = Permission.check_feature_permission(feature,params[:id])%>
                  <%= feature.title %>
               </div>
                  <% if feature.sub_features.count == 0 %>
                   <%= check_box('parent_feature', "#{feature.id}", options = {:checked => p_access,:class => "parent-select",:id => "feature_#{feature.id}_access_level"}) %>
                  <%else%>
                   <%= check_box('parent_feature', "#{feature.id}", options = {:checked => p_access, :class => "parent-select", disabled: true, :id => "feature_#{feature.id}_access_level"}) %>
                  <% end %>
                </div>
             <div id="sub_feature_index_<%= feature.id %>">
                  <% feature.sub_features.each do |sub_feature|%>
                   <div class="field" style="margin: 10px;">
                     <div class="col-sm-6 col-md-6 col-lg-6 Pr0">
                      <% access = Permission.check_feature_permission(sub_feature,params[:id])%>
                      <%= sub_feature.title %>
                     </div>
                     <%= check_box('sub_feature', "#{sub_feature.id}", options = {:checked => access,:class => "sub_case",:id => "sub_case_#{feature.id}"}) %>
                   </div>
                <% end %>
             </div>
             <br>
            <% end %>
            <div class="btn-wrap text-center btn-update-info">
               <%= submit_tag 'Update',:class=> 'button medium orange'%>
               <%=link_to 'Back','/admin/permissions',:class=>'button medium orange'%>
            </div>
        <% end %>
        </div>
    </div>
  </div>
</div>

rvm_2_1_1/current/app/views/shared/_flash_message.html.erb
<% if alert.present?%>
    <div id="flash_message" class="flash-message">
    <div class="alert alert-warning fade in">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
      <strong><span id="msg_container"><%= alert %></span></strong>
    </div>
  </div>
<% end %>

<% if flash[:non_fade_notice].present?%>
  <div id="flash_message" class="flash-message">
    <div class="alert alert-warning fade in">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
      <strong><span id="msg_container"><%= flash[:non_fade_notice] %></span></strong>
    </div>
  </div>
<%end%>

<% if flash[:notice].present? || params[:notice]%>
  <div id="flash_message" class="flash-message">
    <div class="alert alert-warning fade in">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
      <strong>
        <span id="msg_container">
          <%= params[:notice].present? ? params[:notice] : flash[:notice]%>
        </span>
      </strong>
    </div>
  </div>
<% end %>

<% if flash[:after_logged_in].present? || !params[:after_logged_in].blank?%>
  <div id="flash_message" class="flash-message">
    <div class="alert alert-warning fade in">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
      <strong>
        <span id="msg_container">
          <%= params[:after_logged_in].present? ? params[:after_logged_in] : flash[:after_logged_in] %>
			<% if current_user && current_user.is_valid_email(current_user.email) %><a href='javascript:void(0);' onclick="click_bus(<%= current_user.business_type_id%>,'<%= user_plan_billinginfo(current_user)[1]%>','<%= user_plan_billinginfo(current_user)[0].blank? ? false : true%>'); "><strong>Pay Now</strong></a><% end %>
        </span>
      </strong>
    </div>
  </div>
<% end %>


<style>
 /*.flash-on{padding-top: 110px;}*/
 .flash-off{ padding-top: 70px; }
</style>

rvm_2_1_1/current/app/views/shared/_header.html.erb
<div class="container">
  <div class="navbar-header">
    <a href="/" class="navbar-brand"><%= image_tag("responsive/logo-inquirly.png",alt: "Inquirly")%><!--<img src="/assets/responsive/logo-inquirly.png" alt="Inquirly" />--></a>
  </div>
  <%= render :partial => 'shared/profile_dropdown'%>
 <div id="main-navigation">
  <ul class="nav navbar-nav">
   <% a = controller.controller_name %>
   <% b = controller.action_name %>
   <% if user_signed_in? %>
   <% acc_active = current_user.is_active %>
        <!--<%#if check_listener_permisson == true && @is_listener_activated.blank? %>-->
        <!--<li class="">-->
        <!--<a href="javascript:void(0)" onclick="request_listener()">Request Listener</a>-->
        <!--</li>-->
        <!--<%#end%>-->
        <%#if current_user.business_type_id == 2 && @is_listener_activated.present?%>
        <%if check_listener_permisson == true%>
            <!--<%# if @is_listener_activated.first.is_active == true %>-->
            <!--<li class="<%#= 'active' if params[:action] == 'listeners_page' %>">-->
            <!--<%#  url = "/share/listeners_page?username=#{@is_listener_activated.first.username}&password=#{@is_listener_activated.first.password }" %>-->
            <!--<%#= link_to "Listen", {action: :listeners_page, controller: :share, username: @is_listener_activated.first.username, password: @is_listener_activated.first.password } %>-->
            <!--<%#= link_to "Listen", url %>-->
            <!--</li>-->
            <!--<%#else%>-->
            <li class=""><a href="<%= ENV["NEW_LISTENER_URL"]%>" onclick="">Listen</a></li>
            <%#end%>
        <%end%>
 <li class="<%= ((a == "question" && (b == "new"|| b=="preview" || b=="create" || b=="edit" || b == "index" ) || (b == "question_list") || (b == "share") || (b == "show")) || (b=="share_question") && (a !="share"))  ? "active" : ""%>" ><a href="<%=question_index_path%>" class="main-navigation">Engage</a></li>
  <li class="<%= (a == "dashboard" && b == "index")  ? "active" : ""%>"><a href="<%= acc_active == true ?  "/dashboard" :"javascript:void(0)"%>">Act</a></li>
        <% if current_user.business_type_id.to_i ==  3 %><li class=""><a href="<%= ENV["DISTRIBUTE_URL"]%>" onclick="">Distribute</a></li><% end %>
  <% else %>
  <li><a href="/">Home</a></li>
  <li><a href="#" class="main-navigation">How it Works</a></li>
  <li class="sign-in"><a data-toggle="modal" href="#myModal" class="main-navigation" id="user-sign-in">Sign in</a></li>
  <% end %>
</ul>
</div>
</div>

<div class="modal fade" id="pending_listener" aria-hidden="true" tabindex='-1'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          &nbsp;
        </button>
        <h4 class="modal-title">Listener</h4>
      </div>
      <div class="modal-body" id="listener_request_body">
        <label class="text-center listener-success-text">Listener module not yet activated for this account.</label>
      </div>
      <div class="modal-footer">
        <div class="text-center">
          <a href="javascript:void(0);" id="btnYes" class="button medium orange" data-dismiss="modal">Close</a>
        </div>
      </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
jQuery('#pending_listener').on('shown.bs.modal', function (e) {
  jQuery(".modal-backdrop").remove();
});
</script>

rvm_2_1_1/current/app/views/shared/_high_chart_display.html.erb
<%content_for :page_specific_head_content do%>
 <%= javascript_include_tag "responsive/highchart", "responsive/exporting"%>
 <%end%>
<div class="response-graph" id="dash_board_chart"></div>
<script>

  jQuery(function()
  {
    var yaxies = '<%= @chart_date_collection%>';
    yaxies = yaxies.substring(1,yaxies.length-1);
   <% if @chart_view_type == "bar_chart"%>

      jQuery('#dash_board_chart').highcharts({
        chart: {
          type: 'column'
        },
        title: {
          text: 'Views and Responses'
        },
        subtitle: {
          text: 'Source: inquirly.com'
        },
        xAxis: {
          categories: yaxies.replace(/&quot;/g,"").split(","),
          title: { text: "<%=@xaxis_label%>" }
        },
        yAxis: {
          allowDecimals: false,
          min: 0,
          title: {
            text: 'Count'
          }
        },
        tooltip: {
          valueDecimals: 5,
          headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
          pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.0f}</b></td></tr>',
          footerFormat: '</table>',
          shared: true,
          useHTML: true
        },
        plotOptions: {
          column: {
            pointPadding: 0.2,
            borderWidth: 0
          }
        },
        series: [{
            name: 'Views',
            data: <%=@chart_view_counts.map{|x| x.to_i} %>

          }, {
            name: 'Responses',
            data: <%= @chart_response_counts.map{|x| x.to_i} %>

          }]

      });

<%else%>
      jQuery('#dash_board_chart').highcharts({
        chart: {
          type: 'line'
        },
        title: {
          text: 'Views and Responses Count',
          x: -20 //center
        },
        subtitle: {
          text: 'Source: inquirly.com',
          x: -20
        },
        xAxis: {
          title: { text: "<%=@xaxis_label%>" },
          categories: [<% @chart_date_collection.each do |x| %>'<%= x %>',<% end %>],
          labels: {
            rotation: -45,
            align: 'right'
          },
        },
        yAxis: {
          allowDecimals: false,
          min :0,
          title: {
            text: 'Count'
          },
          plotLines: [{
              value: 0,
              width: 1,
              color: '#808080'
            }]
        },
        tooltip: {
          valueDecimals: 0,
          valueSuffix: ''
        },
        legend: {
          layout: 'vertical',
          align: 'right',
          verticalAlign: 'middle',
          borderWidth: 0
        },
        series: [{
            name: 'Views count',
            data: <%=@chart_view_counts.map{|x| x.to_i} %>
          }, {
            name: 'Responses count',
            data: <%= @chart_response_counts.map{|x| x.to_i} %>
          }]

      });
<%end%>
  });
</script>

rvm_2_1_1/current/app/views/shared/_home_footer.html.erb
<div class="footer">
	<div class="container login-wrap">
		<div class="row">
		  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			<div class="footer-txt text-left">Copyright Inquirly <%= Time.now.utc.year %>. All rights reserved.</div>
		  </div>		  
		</div>
	</div>
</div>

rvm_2_1_1/current/app/views/shared/_modal_sentimental_analysis.html.erb
  <div class="modal fade" id="sentimental_report_modal" aria-hidden="true">
    <div class="modal-dialog signup">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &nbsp;
          </button>
          <h4 class="modal-title" id="modal-title">Keywords List</h4>
        </div>
        <div class="modal-body popup-wrapper">
          <div class="container" id="modal-body-content">
            <div id="modal-content-display" class="sentiment-report">
              The requested content cannot be loaded. Please try again later.
            </div>
            <div class="key-words" id="sentimental_keywords_list" style="display:none">
                  <% if status != "dashboard" %>
                    <%= render "keywords", :keywords => keywords %>
                  <%end%>
            </div>
            <div class="key-words" id="sentimental_comments_list" style="display:none">
              <% if status != "dashboard" %>
                  <%=render "comments", :comments => comments %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<style>
  #sentimental_report_modal .modal {
    overflow-y: hidden;
  }
</style>

rvm_2_1_1/current/app/views/shared/_profile_dropdown.html.erb
<% if user_signed_in? %>
    <div class="user-info clearfix">
      <a href="javascript:void(0);"><%=image_tag("#{current_user.attachment.present? ? current_user.attachment.image.url(:thumb) :'responsive/user.jpg'}",class: "user-picture img-circle", height: "35", width: "35")%><span><%=current_user.first_name%></span> <span class="arrow-down"></span> </a>
      <div class="sub-menu">
        <%=form_tag '/account/account_attachment', :method=>:post ,:multipart=>true,:id=>"account_attachment" do %>
            <div class="change-profile-img">Change Display Image
              <input type="file" name="image" class="profile-img-upload" id="company_attachment" onchange ="validateFiles(this);" max_file_size ="2.megabytes"/>
            </div>
            <input type="hidden" value="<%= current_user.id%>" name="account_id" readonly />
            <input type="hidden" value="company_logo" name="step" readonly />
        <%end%>
        <%= link_to "Change Plan", "/payments/merchant_test" %>
        <%= link_to "Settings", edit_user_registration_path %>
        <%= link_to "Admin", tenants_path %>
        <a href="<%=ENV["FRESH_DESK_URL"]%>" target="_blank" >Help</a>
        <%= link_to "Logout", destroy_user_session_path, onclick: "deleteCookie('socialCookie')", class: "last" %>
      </div>
    </div>
<% end %>