rvm_2_1_1/current/config/routes.rb
InquirlyNew::Application.routes.draw do

  #### Landing Page and Auth Routes ####

  devise_scope :user do
    authenticated :user do
      root 'application#home', as: :authenticated_root
    end

    unauthenticated :user do
      root  'home#index'
    end
  end
  
  devise_for :users, :controllers => {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations", unlocks: "users/unlocks"}, :path_names => {sign_in: "login", sign_up: "register"}

  devise_scope :user do
    match "/users/auth/facebook/callback", :to => "users/omniauth_callbacks#facebook", via: :get
    match '/users/auth/twitter/callback' => "users/omniauth_callbacks#twitter", via: :get
    match '/users/auth/google_oauth2/callback' => "users/omniauth_callbacks#google", via: :get
    match '/users/auth/linkedin/callback' => "users/omniauth_callbacks#linkedin", via: :get
    match 'auth/:provider/failure', :to => "users/omniauth_callbacks#failure", via: :get
    match '/users/confirmation', :to => "users/confirmations#create", :via => :post
    match '/users/confirmation/new', :to => "users/confirmations#new", :via => :get
    match '/users/confirmation', :to => "users/confirmations#show", :via => :get
    match '/users/validate_user', :to => "users/sessions#validate_user_data", :via => :post
    match '/users/fb_pages', :to => "users/omniauth_callbacks#fb_pages", :via => :get
    match '/users/save_fb_pages', :to => "users/omniauth_callbacks#save_fb_pages", :via => :post
    match '/users/remove_fb_session', :to => "users/omniauth_callbacks#remove_fb_session", :via => :get
    match '/users/linkedin_pages', :to => "users/omniauth_callbacks#linkedin_pages", :via => :get
    match '/users/save_linkedin_pages', :to => "users/omniauth_callbacks#save_linkedin_pages", :via => :post
    match '/users/remove_linkedin_session', :to => "users/omniauth_callbacks#remove_linkedin_session", :via => :get
  end

  resources :home do
    collection do
      get 'signup', to: 'home#signup_form'
      get 'signin', to: 'home#signin_form'
      get 'forgot_password', to: 'home#forgot_password_form'
      post 'save_referrer'
      post 'fetch_short_url'
    end
  end

  get '/signup' => 'home#signup_form'
  get '/shorten_link' => 'home#shorten_link'

  #### Admin Login Routes ####

  namespace :admin do
    resources :pricing_plans
    resources :permissions
    resources :action_lists
    resources :client_settings do
      collection do
        get 'user_client_settings'
      end
    end
    resources :users, controller: "manage_users" do
      collection do
        post 'change_status'
      end
    end
    resources :manage_clients do
      collection do
        get 'plan_settings'
        get 'client_plan_details'
        post 'change_client_status'
        post 'save_client'
        post 'save_client_company'
        post 'save_client_pricing_plan'
        get 'client_signup'
        post 'update_client_company'
      end
      get 'show_users'
      get 'show_tenants'
      get 'edit_tenant'
      put 'update_tenant'
      get 'download_client_detail'
    end
  end
  match 'admin/manage_clients/:client_id/client_company', :to => "admin/manage_clients#client_company", via: :get
  match 'admin/manage_clients/:client_id/client_pricing_plan', :to => "admin/manage_clients#client_pricing_plan", via: :get

  resources :payments do
    collection do
      post 'update_payment_details'
      get 'get_user_emails'
    end
  end

  #### EMail and SMS Blast API Routes ####

  namespace :api do
    resources :campaigns do
      collection do
        post 'email_blast'
        post 'sms_blast'
      end
    end
  end

  resources :manage_roles do
    collection do
      post 'update_permissions'
      get 'role_permissions'
    end
  end

  #### Mobile API Routes ####

  namespace :rest do
    devise_for :session do
      post '/authenticate',  to:'sessions#create'
    end
    match '/getConfigData', to: 'power_share#social_accounts', as: :social_accounts, via: :post
    match '/powerShare', to: 'power_share#power_share', as: :power_share, via: :post
    match '/getShareQueue', to: 'power_share#get_share_queue', as: :get_share_queue, via: :post
    match '/getShareHistory', to: 'power_share#get_share_history', as: :get_share_history, via: :post
    match '/getReachData', to: 'power_share#get_reach_data', as: :get_reach_data, via: :post
    match '/deletePost', to: 'power_share#delete_post', as: :delete_post, via: :post
    match '/reschedulePost', to: 'power_share#reschedule_post', as: :reschedule_post, via: :post
    match '/getS3Config', to: 'power_share#get_s3_config', as: :get_s3_config, via: :post
    match '/getRecipients', to: 'power_share#get_recipients', as: :get_recipients, via: :post
    match '/getCampaigns', to: 'power_share#get_campaigns', as: :get_campaigns, via: :post
    match '/getSessionInfo', to: 'power_share#get_session_info', as: :get_session_info, via: :post
    match '/updateCampaignState', to: 'power_share#update_campaign_state', as: :update_campaign_state, via: :post
    match '/getApprovalPost', to: 'power_share#get_approval_post', as: :get_approval_post, via: :post
  end

  ##### Angular Routes ####

  resources :configurations do
    collection do
      get 'social_configure'
      post 'customise_campaign'
      get 'get_campaign_styles'
      get 'get_user_actions'
      get 'beacons_list'
      post 'create_beacon'
      post 'update_beacon'
      post 'change_status'
      get 'qr_code_list'
      post 'create_qr_code'
      post 'update_qr_code'
      get 'download_qr_code'
      post 'change_qr_status'
      get 'get_schedule_types'
      post 'add_slot'
      post 'remove_slot'
      post 'update_active_days'
      post 'update_schedule'
      post 'save_schedule'
      post 'pricing_plan_configure'
    end
  end

  resources :companies do
    collection do
      get 'get_tags'
      post 'get_company_info'
    end
  end

  resources :account do
    collection do
      get 'payment_details'
      get 'user_settings'
      post 'update_password'
      post 'update_user_details'
      post 'upload_profile_image'
      post 'destroy_profile_image'
      get  'user_details'
      post  'invite_user'
      get 'user_permissions'
    end
  end

  resources :tenants do
    collection do
      post 'change_tenant_status'
      get 'check_caller_id'
      get 'check_verify_caller_ids'
      get 'load_geo_details'
      post 'create_tenant'
      post 'create_region'
      post 'create_type'
      get 'get_client_plan'
      post 'save_tenant_plan'
      get 'get_tenant_plan'
    end
  end

  resources :corporate_users do
    collection do
      get 'mapping_roles'
      post 'update_user_roles'
      post 'reset_password'
      post 'change_user_status'
      post 'create_user'
      post 'reset_user_password'
      get 'load_regions'
      get 'load_tenants'
    end
  end

  resources :inq_campaigns do
    collection do
      get 'user_channels'
      post 'update_campaign_state'
    end
  end
  
  resources :power_share do
    collection do
     get 'social_accounts'
     post 'fetch_meta_data'
     post 'share_content'
     get 'scheduled_campaigns'
     post 'reschedule_share'
     post 'remove_post'
     get 'power_share_history'
     post 'get_reach'
     post 'archive_post'
     post 'campaign_share'
     post 'remove_schedule'
     post 'get_campaign_channels'
     post 'post_info'
    end
  end

  resources :customers do
    collection do
      get 'get_customer_email'
      get 'email_duplication_check'
      get 'mobile_duplication_check'
      post 'delete_selected'
      post 'remove_social_account'
      get 'all_countries'
      get 'states'
      post 'update_config'
      post 'update_group_info'
      get 'contact_groups'
      get 'group_customers'
      post 'update_group_name'
      post 'remove_group'
      post 'remove_group_customer'
    end
  end

  resources :imports do
    collection do
      post 'create_customer_info'
      get 'csv_template'
      get 'get_upload_status'
    end
  end

  resources :email_activity do
    collection do
      post 'reject_list'
    end
  end

  resources :chat do
    collection do
      get 'identity'
    end
  end

  resources :alert_config do
    collection do
      post 'change_event_status'
      post 'change_channel_status'
      get 'alerts'
      post 'send_alerts'
      post 'update_view_status'
      post 'update_alert_config'
      post 'create_alert_event'
      post 'delete_alert_event'
      post 'get_alert_placeholders'
      post 'update_alert_event'
    end
  end

  resources :dashboard do
    collection do
      post 'get_businesses_info'
      post 'user_engaged_results'
      post 'planner_details'
      get 'post_reviews'
      get 'alerts'
      get 'post_revision'
      post 'get_revision_info'
      get 'get_piwik_info'
    end
  end
end

rvm_2_1_1/current/app/models/pricing_plan.rb
class PricingPlan < ActiveRecord::Base
  has_many :pricing_plan_channels, as: :plannable
  belongs_to :currency

  validates :name, presence: {:message => "Please enter plan name."}
  validates :name, uniqueness: {:scope => :country, :message => "Plan already exists."}

  def create_or_update_channel_list(channels_id)
    PricingPlanChannel.where(plannable_id: self.id).delete_all
    channels_id && channels_id.each do |channel_id|
      PricingPlanChannel.create(plannable_type: self.class.try(:model_name).try(:name), plannable_id: self.id, channel_id: channel_id)
    end
  end

  def update_pricing_details(params,channels_id)
    ok = self.update_attributes(params)
    ok && channels_id ? self.create_or_update_channel_list(channels_id) : ok
  end

  def self.fetch_client_config(params)
    user = User.where(id: params[:client_id]).first
    response = {}
    unless user.overall_plans.blank?
      if user.parent_id == 0
        plan = user.active_pricing_plan
      else
        if user.tenant_id
          tenant = Tenant.where(id: user.tenant_id).first
          plan = tenant.present? ? tenant.active_tenant_plan : []
        else
          plan = user.client.active_pricing_plan
        end
      end
      unless plan.blank?
       response[:plan_detail] = plan ? JSON.parse(plan.to_json(:except => [:created_at, :updated_at, :exp_date], :methods => [:expiry_date])) : {}
       response[:channels] = plan.pricing_plan_channels ? Channel.where(id: plan.pricing_plan_channels.map(&:channel_id)).map(&:name) : []
      end
    end
    response.blank? ?  {status: 400, error: "You don't have valid pricing plan set. Please contact admin for subscription."} : {status: 200, response: response }
  end

  def channels_name
    Channel.where(id: self.pricing_plan_channels.map(&:channel_id)).map(&:name)
  end

end

rvm_2_1_1/current/app/controllers/admin/pricing_plans_controller.rb
class Admin::PricingPlansController < InheritedResources::Base
  before_action :check_admin_user
  before_filter :authenticate_user_web_api
  before_action :load_channels, only: [:new, :create, :edit, :update]
  layout 'admin_layout'

  def index
    @pricing_plans = PricingPlan.all.order(:id).paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.json { render json: @pricing_plans }
    end
  end

  def show
    @pricing_plan = PricingPlan.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @pricing_plan }
    end
  end

  def new
    @pricing_plan = PricingPlan.new
    respond_to do |format|
      format.html
      format.json { render json: @pricing_plan }
    end
  end

  def edit
    @pricing_plan = PricingPlan.find(params[:id])
  end

  def create
    @pricing_plan = PricingPlan.new(pricing_params)
    respond_to do |format|
      if @pricing_plan.save
        @pricing_plan.create_or_update_channel_list(params[:channels_id])
        format.html { redirect_to admin_pricing_plans_path, notice: 'Pricing plan was successfully created.' }
        format.json { render json: @pricing_plan, status: :created, location: @pricing_plan }
      else
        format.html { render action: "new" }
        format.json { render json: @pricing_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @pricing_plan = PricingPlan.find(params[:id])
    respond_to do |format|
      if @pricing_plan.update_pricing_details(pricing_params, params[:channels_id])
        format.html { redirect_to admin_pricing_plans_path, notice: 'Pricing plan successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pricing_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def pricing_params
    params.require(:pricing_plan).permit(:name, :country, :email_count,:sms_count,:campaigns_count,:customer_records_count,:fb_boost_budget,:currency_id, :is_default, :total_reach)
  end

  def load_channels
    @channels = Channel.all
  end

end

rvm_2_1_1/current/app/views/admin/pricing_plans/_form.html.erb
<div class="tab-content inner">
  <div class="tab-wrapper">
    <div class="row">
      <div class="col-lg-4 col-sm-6 col-md-12 col-xs-12">
        <%= form_for [:admin, @pricing_plan] do |f| %>
            <div class="row">
              <div class="col-lg-12">
                <label>Name</label>
                <div class="form-group">
                  <%= f.text_field :name, :class => "text_field rc_5 form-control input-medium" ,:placeholder => "Plan Name" , :tabindex => 1%>
                  <p><span id="error_first_name" style="width:190px;color: red;"> <%= @pricing_plan.errors && @pricing_plan.errors.messages ? @pricing_plan.errors.messages[:name][0] : '' %></span></p>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12" style="width: 136%">
                <label>Channels</label>
                    <div class="form-group" style="display: inline-block">
                      <% @channels.each do |channel|%>
                        <%= check_box_tag 'channels_id[]', channel.id,(true if selected_channels(@pricing_plan,channel,params)) %>
                        <%= label_tag "channels_id[][#{channel.id}]", channel.name %>
                      <% end %>
                    </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <label>Email Count</label>
                <div class="form-group">
                  <%= f.number_field :email_count, :class => "text_field rc_5 form-control input-medium", :placeholder => "Email Count" , :tabindex => 2 %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <label>SMS Count</label>
                <div class="form-group">
                  <%= f.number_field :sms_count, :class => "text_field rc_5 form-control input-medium", :placeholder => "SMS Count" , :id => "sms_count", :tabindex => 3 %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <label>Campaigns Count</label>
                <div class="form-group">
                  <%= f.number_field :campaigns_count, :class => "text_field rc_5 form-control input-medium" ,:placeholder => "Campaigns Count", :id => "call_count", :tabindex => 4 %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <label>Customer Records Count</label>
                <div class="form-group">
                  <%= f.number_field :customer_records_count, :class => "text_field rc_5 form-control input-medium", :placeholder => "Customer Records Count" , :tabindex => 5 %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12">
                <label>FB Boost budget</label>
                <div class="form-group">
                  <%= f.number_field :fb_boost_budget, :class => "text_field rc_5 form-control input-medium", :placeholder => "FB boost budget" , :tabindex => 6 %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <label>Total Reach</label>
                <div class="form-group">
                  <%= f.number_field :total_reach, :class => "text_field rc_5 form-control input-medium", :placeholder => "Total Reach" , :tabindex => 7 %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <label>Country</label>
                <div class="form-group">
                  <%= f.select :country, options_for_select(Country.all, :selected => selected_country(@pricing_plan)), {}, { :class => 'text_field rc_5 form-control input-medium', :tabindex => 8 } %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <label>Currency</label>
                <div class="form-group">
                  <%= f.select :currency_id, options_from_collection_for_select(Currency.all, :id, :name), {}, { :class => 'text_field rc_5 form-control input-medium', :tabindex => 9 } %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-12">
                <label>Default Plan</label>
                <div class="form-group">
                  <%= f.check_box :is_default, :disabled => @pricing_plan.is_default %>
                </div>
              </div>
            </div>
            <div class="btn-wrap btn-update-info">
              <%= f.submit  "Save", :class => "button medium orange", :tabindex => 10  %>
              <a href="/admin/pricing_plans" class="article" id="back_to_users">Back</a>
            </div>
            </div>
            </div>
        <% end %>
        </div>
</div>
</div>

rvm_2_1_1/current/app/views/admin/pricing_plans/edit.html.erb
<%= render 'form' %>

rvm_2_1_1/current/app/views/admin/pricing_plans/index.html.erb
<div class="row" style="float:right;margin-bottom: 6px;">
  <div class="col-sm-5 col-lg-5 col-md-5">
    <div class="btn-wrap text-right btn-update-info" style="margin-top: 5px;">
      <a href="/admin/pricing_plans/new" class="btn btn-primary">+ Add Plan</a>
    </div>
  </div>
</div>
<div class= "table-responsive" style="margin-top:15px;">
  <table class="table user-table">
    <thead>
    <tr>
      <th class="align-cen">Plan name</th>
      <th class="align-cen">Email Count</th>
      <th class="align-cen">SMS Count</th>
      <th class="align-cen">Campaigns Count</th>
      <th class="align-cen">Customer records count</th>
      <th class="align-cen">FB boost budget</th>
      <th class="align-cen">Total Reach</th>
      <th class="align-cen">Country</th>
      <th class="align-cen">Amount</th>
      <th class="align-cen">Default Plan</th>
      <th class="align-cen" colspan="3">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @pricing_plans.each do |pricing_plan| %>
        <tr>
          <td class="align-cen"><%= pricing_plan.name %></td>
          <td class="align-cen"><%= pricing_plan.email_count %></td>
          <td class="align-cen"><%= pricing_plan.sms_count %></td>
          <td class="align-cen"><%= pricing_plan.campaigns_count %></td>
          <td class="align-cen"><%= pricing_plan.customer_records_count %></td>
          <td class="align-cen"><%= pricing_plan.fb_boost_budget %></td>
          <td class="align-cen"><%= pricing_plan.total_reach %></td>
          <td class="align-cen"><%= country_name(pricing_plan.country) %></td>
          <td class="align-cen"><%= pricing_plan.amount %></td>
          <td class="align-cen">
            <div class="<%= pricing_plan.is_default ? 'client-active' : 'client-deactive' %>">
                <%= pricing_plan.is_default ? 'YES' : 'NO' %>
            </div>
          </td>
          <td class="align-cen">
            <div class="action-items">
              <a href="/admin/pricing_plans/<%= pricing_plan.id %>/edit"><i class="fa fa-edit" aria-hidden="true"></i></a>
            </div>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<div class="row">
  <div class="pull-right">
    <%= will_paginate @pricing_plans, renderer: BootstrapPagination::Rails %>
  </div>
</div>

rvm_2_1_1/current/app/views/admin/pricing_plans/new.html.erb
<%= render 'form' %>

rvm_2_1_1/current/app/views/admin/pricing_plans/show.html.erb
<p>
  <strong>Plan name:</strong>
  <%= @pricing_plan.name %>
</p>

<p>
  <strong>Customer Records count:</strong>
  <%= @pricing_plan.customer_records_count %>
</p>
<p>
  <strong>Email count:</strong>
  <%= @pricing_plan.email_count %>
</p>
<p>
  <strong>Sms count:</strong>
  <%= @pricing_plan.sms_count %>
</p>
<p>
  <strong>Campaigns count:</strong>
  <%= @pricing_plan.campaigns_count %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @pricing_plan.amount %>
</p>


<%= link_to 'Edit', edit_admin_pricing_plan_path(@pricing_plan) %> |
<%= link_to 'Back', admin_pricing_plans_path %>